#Nome da Aplicação
spring.application.name=api-financas

# Conexão com o MySQL local
spring.datasource.url=jdbc:mysql://localhost:3306/financas_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Driver e Dialeto Hibernate/JPA
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# Exibir os comandos SQL no console do IntelliJ (otimo para estudos)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true